In [3]:
'''
資料載入
載入 CSV 檔案
載入 TXT 檔案
載入 EXCEL 檔案
載入 JSON 檔案
'''
# 使用 pandas 套件的 .read_csv() 方法載入 csv 檔案

import pandas as pd
url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends_df.csv"   # 在雲端上儲存了一份 csv 檔案
# 輸入在網址, 下載後點右鍵使用開啟文件的程式開啟 csv 檔案

friends_df = pd.read_csv(url)
friends_df

       characters             stars
0    Rachel Green  Jennifer Aniston
1   Monica Geller     Courteney Cox
2   Phoebe Buffay       Lisa Kudrow
3  Joey Tribbiani      Matt LeBlanc
4   Chandler Bing     Matthew Perry
5     Ross Geller   David Schwimmer

In [4]:
# 使用 pandas 套件的 .read_table() 方法載入 txt 檔案
# 自行指定 sep 參數

import pandas as pd

url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends_df.txt" # 在雲端上儲存了一份 txt 檔案
# txt 檔案內的欄位, 使用 ; 作為分割

friends_df = pd.read_table(url, sep = ";")
friends_df

       characters             stars
0    Rachel Green  Jennifer Aniston
1   Monica Geller     Courteney Cox
2   Phoebe Buffay       Lisa Kudrow
3  Joey Tribbiani      Matt LeBlanc
4   Chandler Bing     Matthew Perry
5     Ross Geller   David Schwimmer

In [5]:
# 使用 pandas 套件的 .read_excel() 方法來載入 excel 檔案

import pandas as pd

url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends_df.xlsx" # 在雲端上儲存了一份 Excel 試算表
friends_df = pd.read_excel(url)
friends_df

       characters             stars
0    Rachel Green  Jennifer Aniston
1   Monica Geller     Courteney Cox
2   Phoebe Buffay       Lisa Kudrow
3  Joey Tribbiani      Matt LeBlanc
4   Chandler Bing     Matthew Perry
5     Ross Geller   David Schwimmer

In [6]:
# JSON 類似 Javascript 裡面的 dictionary

# 使用 pandas 套件的 .read_json() 方法來載入 json 檔案
# Array of JSON , JSON 裡面是 Array的型態

import pandas as pd

url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends_df.json" # 在雲端上儲存了一份 JSON 檔案
friends_df = pd.read_json(url) 
friends_df

       characters             stars
0    Rachel Green  Jennifer Aniston
1   Monica Geller     Courteney Cox
2   Phoebe Buffay       Lisa Kudrow
3  Joey Tribbiani      Matt LeBlanc
4   Chandler Bing     Matthew Perry
5     Ross Geller   David Schwimmer

In [7]:
# 使用 pandas 套件的 .read_json() 方法來載入 json 檔案
# JSON 型態

import pandas as pd

url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends.json" # 在雲端上儲存了一份 JSON 檔案
friends_df = pd.read_json(url)
friends_df

       characters  episodes   genre  seasons             stars
0    Rachel Green       236  Sitcom       10  Jennifer Aniston
1   Monica Geller       236  Sitcom       10     Courteney Cox
2   Phoebe Buffay       236  Sitcom       10       Lisa Kudrow
3  Joey Tribbiani       236  Sitcom       10      Matt LeBlanc
4   Chandler Bing       236  Sitcom       10     Matthew Perry
5     Ross Geller       236  Sitcom       10   David Schwimmer

In [11]:
# 使用 json 套件的 loads() 方法來載入 json 檔案

import urllib.request     # tip1:主要功用是開啟 url, 不需再轉換格式
import json

url = "https://storage.googleapis.com/intro-2-py-ds/data/ch9/friends.json"
with urllib.request.urlopen(url) as json_url:              # tip1:
    friends_dict = json.loads(json_url.read().decode())
print(type(friends_dict))
print("\n")

print("六人行有 %i 季" % friends_dict["seasons"])
for character, star in zip(friends_dict["characters"], friends_dict["stars"]):
    print("%s 由 %s 飾演" % (character, star))

<class 'dict'>


六人行有 10 季
Rachel Green 由 Jennifer Aniston 飾演
Monica Geller 由 Courteney Cox 飾演
Phoebe Buffay 由 Lisa Kudrow 飾演
Joey Tribbiani 由 Matt LeBlanc 飾演
Chandler Bing 由 Matthew Perry 飾演
Ross Geller 由 David Schwimmer 飾演

In [18]:
friends_df.to_csv("D:\writer.csv", index = False)    # 將 data.frame載入到檔案, 且不要輸出 index